"""empty message

Revision ID: 13357b1af87c
Revises: b7a275512b07
Create Date: 2023-11-23 14:51:58.115831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13357b1af87c'
down_revision = 'b7a275512b07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logged_out_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('logged_out_at')

    # ### end Alembic commands ###
