"""empty message

Revision ID: 320c66b14256
Revises: 89ea8ab14d0f
Create Date: 2023-11-23 22:16:20.506998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '320c66b14256'
down_revision = '89ea8ab14d0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_task_view', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('enable_notifications', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('theme_preference', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('theme_preference')
        batch_op.drop_column('enable_notifications')
        batch_op.drop_column('default_task_view')

    # ### end Alembic commands ###
