"""empty message

Revision ID: 65ed8a579e8c
Revises: b26f27b88bce
Create Date: 2023-12-07 13:16:57.921868

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '65ed8a579e8c'
down_revision = 'b26f27b88bce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('theme_preference')
        batch_op.drop_column('default_task_view')
        batch_op.drop_column('enable_notifications')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enable_notifications', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('default_task_view', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('theme_preference', mysql.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
