"""empty message

Revision ID: 71e3b942134a
Revises: b35a9f6dea6c
Create Date: 2023-11-23 17:32:40.005246

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '71e3b942134a'
down_revision = 'b35a9f6dea6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('username')
        batch_op.drop_column('user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('username', mysql.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
