"""add created_at column to User model

Revision ID: 79645f2a3465
Revises: 2401f25241cd
Create Date: 2023-11-18 02:02:10.816012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79645f2a3465'
down_revision = '2401f25241cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_at')
    # ### end Alembic commands ###
