"""empty message

Revision ID: 89ea8ab14d0f
Revises: 71e3b942134a
Create Date: 2023-11-23 17:40:59.209672

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '89ea8ab14d0f'
down_revision = '71e3b942134a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', mysql.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
