"""Add created_at and updated_at to User

Revision ID: 97d7f28bc48a
Revises: d5a17fa1a672
Create Date: 2023-12-14 14:19:03.104819

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '97d7f28bc48a'
down_revision = 'd5a17fa1a672'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('enable_notifications')
        batch_op.drop_column('theme_preference')
        batch_op.drop_column('logged_out_at')
        batch_op.drop_column('receive_notifications')
        batch_op.drop_column('default_task_view')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_task_view', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('receive_notifications', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('logged_out_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('theme_preference', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('enable_notifications', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
