"""empty message

Revision ID: a750231dab98
Revises: bbc75d6ef59b
Create Date: 2023-11-24 04:46:12.900916

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a750231dab98'
down_revision = 'bbc75d6ef59b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('recurrence')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurrence', mysql.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
