"""update option for tasks

Revision ID: bb32f0b70627
Revises: 2847507d36e9
Create Date: 2023-11-18 04:12:03.115928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb32f0b70627'
down_revision = '2847507d36e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'updated_at')
    # ### end Alembic commands ###
